declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('@virgo-ui/vue')['AAlert']
    AAvatar: typeof import('@virgo-ui/vue')['AAvatar']
    ABadge: typeof import('@virgo-ui/vue')['ABadge']
    ABaseInput: typeof import('@virgo-ui/vue')['ABaseInput']
    ABtn: typeof import('@virgo-ui/vue')['ABtn']
    ACard: typeof import('@virgo-ui/vue')['ACard']
    ACheckbox: typeof import('@virgo-ui/vue')['ACheckbox']
    AChip: typeof import('@virgo-ui/vue')['AChip']
    AConfig: typeof import('@virgo-ui/vue')['AConfig']
    ADataTable: typeof import('@virgo-ui/vue')['ADataTable']
    ADialog: typeof import('@virgo-ui/vue')['ADialog']
    ADrawer: typeof import('@virgo-ui/vue')['ADrawer']
    AFloating: typeof import('@virgo-ui/vue')['AFloating']
    AIcon: typeof import('@virgo-ui/vue')['AIcon']
    AInput: typeof import('@virgo-ui/vue')['AInput']
    AList: typeof import('@virgo-ui/vue')['AList']
    AListItem: typeof import('@virgo-ui/vue')['AListItem']
    ALoader: typeof import('@virgo-ui/vue')['ALoader']
    ALoadingIcon: typeof import('@virgo-ui/vue')['ALoadingIcon']
    AMenu: typeof import('@virgo-ui/vue')['AMenu']
    ARadio: typeof import('@virgo-ui/vue')['ARadio']
    ARating: typeof import('@virgo-ui/vue')['ARating']
    ASelect: typeof import('@virgo-ui/vue')['ASelect']
    ASpinner: typeof import('@virgo-ui/vue')['ASpinner']
    ASwitch: typeof import('@virgo-ui/vue')['ASwitch']
    ATab: typeof import('@virgo-ui/vue')['ATab']
    ATable: typeof import('@virgo-ui/vue')['ATable']
    ATabs: typeof import('@virgo-ui/vue')['ATabs']
    ATextarea: typeof import('@virgo-ui/vue')['ATextarea']
    ATooltip: typeof import('@virgo-ui/vue')['ATooltip']
    ATypography: typeof import('@virgo-ui/vue')['ATypography']
    AView: typeof import('@virgo-ui/vue')['AView']
    AViews: typeof import('@virgo-ui/vue')['AViews']
  }
}

export  {}