declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('virgo-vue')['AAlert']
    AAvatar: typeof import('virgo-vue')['AAvatar']
    ABadge: typeof import('virgo-vue')['ABadge']
    ABaseInput: typeof import('virgo-vue')['ABaseInput']
    ABtn: typeof import('virgo-vue')['ABtn']
    ACard: typeof import('virgo-vue')['ACard']
    ACheckbox: typeof import('virgo-vue')['ACheckbox']
    AChip: typeof import('virgo-vue')['AChip']
    AConfig: typeof import('virgo-vue')['AConfig']
    ADataTable: typeof import('virgo-vue')['ADataTable']
    ADialog: typeof import('virgo-vue')['ADialog']
    ADrawer: typeof import('virgo-vue')['ADrawer']
    AFloating: typeof import('virgo-vue')['AFloating']
    AIcon: typeof import('virgo-vue')['AIcon']
    AInput: typeof import('virgo-vue')['AInput']
    AList: typeof import('virgo-vue')['AList']
    AListItem: typeof import('virgo-vue')['AListItem']
    ALoader: typeof import('virgo-vue')['ALoader']
    ALoadingIcon: typeof import('virgo-vue')['ALoadingIcon']
    AMenu: typeof import('virgo-vue')['AMenu']
    ARadio: typeof import('virgo-vue')['ARadio']
    ARating: typeof import('virgo-vue')['ARating']
    ASelect: typeof import('virgo-vue')['ASelect']
    ASpinner: typeof import('virgo-vue')['ASpinner']
    ASwitch: typeof import('virgo-vue')['ASwitch']
    ATab: typeof import('virgo-vue')['ATab']
    ATable: typeof import('virgo-vue')['ATable']
    ATabs: typeof import('virgo-vue')['ATabs']
    ATextarea: typeof import('virgo-vue')['ATextarea']
    ATooltip: typeof import('virgo-vue')['ATooltip']
    ATypography: typeof import('virgo-vue')['ATypography']
    AView: typeof import('virgo-vue')['AView']
    AViews: typeof import('virgo-vue')['AViews']
  }
}

export { }

